### ISSUE TITLE
SOF 2.2 Release Checklist

### ISSUE THREAD

**Issue by mengdonglin** [thesofproject/sof#5797]
Pre RC1 Steps:
- [x] tag any of the issues and feature lists with milestone v2.2  https://github.com/thesofproject/sof/issues?q=is%3Aopen+is%3Aissue+milestone%3Av2.2
- [x] Align on FW and topology layout update in https://github.com/thesofproject/sof-bin
- [x] Choose a SOF commit on main branch as candidate for branch out stable-v2.2
- [x] Choose a Zephyr commit on main branch as candidate for branch out a copy for SOF v2.2
- [x] Testing & sign off this commit
- [x] branch out stable-v2.2

RC1 Steps: 
- [x] Cherry pick critical bug fixings and features to stable-v2.2 for RC1
- [x] Perform FW security scan and fix opens
- [x] Update Zephyr branch for v2.2 
- [x] Testing & sign off
- [x] Tag v2.2-rc1
- [x] Make rc1 release on https://github.com/thesofproject/sof/releases
- [x] signing of the FW, upload FW and topology binaries to internal release folder
- [x] Update binary release script
- [x] Make rc1 release on https://github.com/thesofproject/sof-bin
- [x] Send the mail to ALSA mailing list?

Final 2.2 steps:
- [ ] Cherry pick critical bug fixings to stable-v2.2
- [ ] Testing & sign off
- [ ] Tag v2.2
- [ ] Make release on https://github.com/thesofproject/sof/releases
- [ ] signing of the FW, upload FW and topology binaries to internal release folder
- [ ] Make release on https://github.com/thesofproject/sof-bin
- [ ] Send the mail to ALSA mailing list?
- [ ] Declare the release on https://www.sofproject.org/blog/

**Comment by marc-hb** [comment]
Should this be part of https://github.com/thesofproject/sof-bin/blob/main/HOWTO-new-release.md ?

**Comment by mengdonglin** [comment]
> Should this be part of https://github.com/thesofproject/sof-bin/blob/main/HOWTO-new-release.md ?

@marc-hb Do you mean we should list the required steps in https://github.com/thesofproject/sof-bin/blob/main/HOWTO-new-release.md?

**Comment by marc-hb** [comment]
Yes or as another, template file close to it. Then for each release we can copy the template into a new issue like this one.

This would make the template reviewed, version controlled and available outside Github.

**Comment by mengdonglin** [comment]
> Yes or as another, template file close to it. Then for each release we can copy the template into a new issue like this one.
> 
> This would make the template reviewed, version controlled and available outside Github.

@marc-hb Okay. I can work on PR to update in https://github.com/thesofproject/sof-bin/blob/main/HOWTO-new-release.md

**Comment by lgirdwood** [comment]
Stable branch created.

**Comment by kv2019i** [comment]
https://github.com/thesofproject/sof/releases/tag/v2.2-rc1 created

**Comment by lgirdwood** [comment]
@mengdonglin any updates here ?

**Comment by mengdonglin** [comment]
Closing this as v2.2 was release.
