### ISSUE TITLE
SOF 2.5 Release Checklist

### ISSUE THREAD

**Issue by kv2019i** [thesofproject/sof#7066]
Estimated Timeline (in ISO 8601 weeks)
- stable-v2.5 branch 2023-W10
- RC1 2023-W11
- final tag 2023-W12 
- release with product binaries 2023-W13-

Pre RC1 Steps:
- [x] tag any of the issues and feature lists with milestone v2.X  https://github.com/thesofproject/sof/issues?q=is%3Aopen+is%3Aissue+milestone%3Av2.5
- [x] Choose a SOF commit on main branch as candidate for branch out stable-v2.X (done, 528c7ebce0c1bcb50bcffeb30fc3be8cf549a98d )
- [x] Testing & sign off this commit
- [x] branch out stable-v2.5 , target WW10 

RC1 Steps: 
- [x] Cherry pick critical bug fixings and features to stable-v2.X for RC1
- [x] Perform FW security scan and fix opens -> done, fixed integrated in https://github.com/thesofproject/sof/pull/7283
- [x] Testing & sign off
- [x] Tag v2.5-rc1  -> https://github.com/thesofproject/sof/releases/tag/v2.5-rc1
- [x] Make rc1 release on https://github.com/thesofproject/sof/releases

RC1 Vendor specific Steps / Intel:
- [ ] signing of the FW, upload FW and topology binaries to internal release folder -> skipped for v2.5
- [ ] Update binary release script -> skipped for v2.5
- [ ] Make rc1 release on https://github.com/thesofproject/sof-bin -> skipped for v2.5

Final release steps:
- [x] Cherry pick critical bug fixings to stable-v2.X
- [x] Testing & sign off
- [x] Tag v2.X -> https://github.com/thesofproject/sof/releases/tag/v2.5
- [x] Make release on https://github.com/thesofproject/sof/releases

Final release, vendor specific steps / Intel:
- [x] signing of the FW, upload FW and topology binaries to internal release folder
- [x] Make release on https://github.com/thesofproject/sof-bin

Final steps:
- [x] Declare the release on https://www.sofproject.org/blog/

Cleanup:
- [x] Move any unfinished issues tagged to next milestone (the vX.Y milestone tags)

**Comment by kv2019i** [comment]
SOF2.5 stable branch created https://github.com/thesofproject/sof/tree/stable-v2.5 
Target to tag rc1 next week.

**Comment by marc-hb** [comment]
> stable-v2.5 branch WW10

Lucky us, Intel WW and standard WW numbers seem to match in 2023 :-)

https://www.intel.com/content/www/us/en/supplier/resources/misc/documents/workweek-calendar.html

**Comment by dbaluta** [comment]
@kv2019i let's not forget to actually add a 'tag' for this branch so that version shown in dmesg is correct. I think we forgot that for stable-v2.4

**Comment by kv2019i** [comment]
@dbaluta Thanks, now fixed. I also added it to the checklist so the next person doing releases remembers to do this as well. I do hate this mechanism to set version numbers from git tags. ;)

**Comment by marc-hb** [comment]
>  I do hate this mechanism to set version numbers from git tags. ;)

- #6952
> I closed this PR draft - I will prepare a new solution based on a manually changed *.h file containing the current version of FW. New solution will be prepared in the new PR.

**Comment by kv2019i** [comment]
SOF 2.5 is out  https://github.com/thesofproject/sof/releases/tag/v2.5 ! All issues tagged to v2.5 are either done or rescheduled to a later release, so this checklist can be considered complete and closing the item.
