### ISSUE TITLE
SOF 2.7 Release Checklist

### ISSUE THREAD

**Issue by alex-cri** [thesofproject/sof#8017]
Planned Timeline
- Stable v2.7 Branch – ww35 (August 28 to Sept. 1)
- RC1 – ww36 (Sept. 4 to Sept. 8) 
- Final Tag – ww37 (Sept. 11 to Sept. 15)
- Target Release – ww38 (Sept. 18 to Sept. 22)
- Overflow week (in case multiple RCs are required) – ww39 (Sept. 25 to Sept. 29)

Pre-RC1 Steps:
- [x] Tag features and issue list with milestone v2.7: https://github.com/thesofproject/sof/milestones/v2.7
- [x] Choose a SOF commit on main branch as candidate for stable branch
- [x] Testing & sign off
- [x] Branch stable v2.7 -> https://github.com/thesofproject/sof/tree/stable-v2.7

RC1 Steps:
- [x] Cherry pick critical features and bug fixes to stable-v2.7 for RC1
- [x] Perform FW security scan and fix opens
- [x] Testing & sign off
- [x] Tag v2.7-RC1

Final Release Steps:
- [x] Cherry pick critical features and bug fixes to stable-v2.7
- [x] Testing & sign off
- [x] Tag v2.7
- [x] Publish release on https://github.com/thesofproject/sof/releases

Final Release, vendor specific steps / Intel:
- [x] Production sign FW, upload FW and topology binaries to internal release folder
- [x] Publish release on https://github.com/thesofproject/sof-bin/blob/main/HOWTO-new-release.md

Final Steps:
- [x] Declare the v2.7 release on https://www.sofproject.org/blog/
- [x] Move any unfinished issues to next milestone

**Comment by kv2019i** [comment]
v2.7 release is out, enjoy! https://github.com/thesofproject/sof/releases/tag/v2.7
