### ISSUE TITLE
SOF 2.8 Release Checklist

### ISSUE THREAD

**Issue by kv2019i** [thesofproject/sof#8363]
Planned Timeline
- Stable v2.8 Branch – ww47 (Nov 20 to Nov 26)
- RC1 – ww49 (Dec 4 to Dec 10) 
- Final Tag – ww50 (Dec 11 to Dec 17)
- Target Release – ww51 (Dec 18 to Dec 24)
- Overflow week (in case multiple RCs are required) – ww52-01

Pre-RC1 Steps, Creation of Stable Branch
- [x] Tag features and issue list with milestone v2.8: https://github.com/thesofproject/sof/milestones/v2.8
- [x] Choose a SOF commit on main branch as candidate for stable branch
- [x] Testing & sign off
- [x] Branch stable v2.8 -> https://github.com/thesofproject/sof/tree/stable-v2.8

RC1 Steps:
- [x] Cherry pick critical features and bug fixes to stable-v2.8 for RC1
- [x] Perform FW security scan and fix opens
- [x] Testing & sign off
- [x] Tag v2.8-RC1 -> https://github.com/thesofproject/sof/tree/v2.8-rc1

Final Release Steps:
- [x] Cherry pick critical features and bug fixes to stable-v2.8
- [x] Testing & sign off
- [x] Tag v2.8 -> https://github.com/thesofproject/sof/tree/v2.8
- [x] Publish release on https://github.com/thesofproject/sof/releases

Final Release, vendor specific steps / Intel:
- [x] Production sign FW, upload FW and topology binaries to internal release folder
- [x] Publish release on https://github.com/thesofproject/sof-bin/blob/main/HOWTO-new-release.md

Final Steps:
- [x] Declare the v2.8 release on https://www.sofproject.org/blog/
- [x] Move any unfinished issues to next milestone

**Comment by kv2019i** [comment]
Release is out https://www.sofproject.org/blog/2023/12/18/sof-2-8-0-is-here/ !
