### ISSUE TITLE
SOF 2.9 Release Checklist

### ISSUE THREAD

**Issue by kv2019i** [thesofproject/sof#8696]
Planned Timeline
- Stable v2.9 Branch – ww09 (Feb 26 to March 1)
- RC1 – ww10 (March 3 to March 8) 
- Final Tag – ww11 (March 11 to March 15)
- Target Release – ww12 (March 18 to March 22)
- Overflow week (in case multiple RCs are required) – ww13

Pre-RC1 Steps, Creation of Stable Branch
- [x] Tag features and issue list with milestone v2.9: https://github.com/thesofproject/sof/milestones/v2.9
- [x] Choose a SOF commit on main branch as candidate for stable branch
- [x] Testing & sign off
- [x] Branch stable v2.9 -> https://github.com/thesofproject/sof/tree/stable-v2.9

RC1 Steps:
- [x] Cherry pick critical features and bug fixes to stable-v2.9 for RC1
- [x] Perform FW security scan and fix opens
- [x] Testing & sign off
- [x] Tag v2.9-RC1 -> https://github.com/thesofproject/sof/tree/v2.9-rc1

Final Release Steps:
- [x] Cherry pick critical features and bug fixes to stable-v2.9
- [x] Testing & sign off
- [x] Tag v2.9 -> https://github.com/thesofproject/sof/tree/v2.9
- [ ] Publish release on https://github.com/thesofproject/sof/releases

Final Release, vendor specific steps / Intel:
- [x] Production sign FW, upload FW and topology binaries to internal release folder
- [x] Publish release on https://github.com/thesofproject/sof-bin/blob/main/HOWTO-new-release.md

Final Steps:
- [x] Declare the v2.9 release on https://www.sofproject.org/blog/
- [x] Move any unfinished issues to next milestone

**Comment by kv2019i** [comment]
Stable branch created at https://github.com/thesofproject/sof/tree/stable-v2.9 . Please submit bugfixes and other critical backports as pull requests against stable-v2.9 branch.

**Comment by kv2019i** [comment]
rc1 tagged https://github.com/thesofproject/sof/tree/v2.9-rc1

**Comment by kv2019i** [comment]
v2.9 tagged https://github.com/thesofproject/sof/tree/v2.9 . Binary package ETA next week
