### ISSUE TITLE
SOF 2.10 Release Checklist

### ISSUE THREAD

**Issue by kv2019i** [thesofproject/sof#9037]
Planned Timeline (updated on May 28th)
- Stable v2.10 Branch – ww22->ww23.3 (**5th June**)
- RC1 – ww23->ww24 -> **14th June -> actual 20th June**
- Final Tag – ww24->25  -> **21th June -> 27th June **
- Target Release – ww25->26 -> **28th June**
- Overflow week (in case multiple RCs are required) – ww27

Pre-RC1 Steps, Creation of Stable Branch
- [x] Tag features and issue list with milestone v2.10: https://github.com/thesofproject/sof/milestones/v2.10
- [x] Choose a SOF commit on main branch as candidate for stable branch
- [x] Testing & sign off
- [x] Branch stable v2.10 -> https://github.com/thesofproject/sof/tree/stable-v2.10

RC1 Steps:
- [x] Cherry pick critical features and bug fixes to stable-v2.10 for RC1
- [x] Perform FW security scan and fix opens
- [x] Testing & sign off
- [x] Tag v2.10-RC1 -> https://github.com/thesofproject/sof/tree/v2.10-rc1

Final Release Steps:
- [x] Cherry pick critical features and bug fixes to stable-v2.10
- [x] Testing & sign off
- [x] Tag v2.10
- [x] Publish release on https://github.com/thesofproject/sof/releases

Final Release, vendor specific steps / Intel:
- [x] Production sign FW, upload FW and topology binaries to internal release folder
- [x] Publish release on https://github.com/thesofproject/sof-bin/blob/main/HOWTO-new-release.md

Final Release, vendor specific steps / OtherVendor:
- add steps here

Final Steps:
- [x] Declare the v2.10 release on https://www.sofproject.org/blog/
- [x] Move any unfinished issues to next milestone

**Comment by kv2019i** [comment]
Stable tree branched https://github.com/thesofproject/sof/tree/stable-v2.10

**Comment by kv2019i** [comment]
rc1 tagged https://github.com/thesofproject/sof/tree/v2.10-rc1 . Updated the timeline for remaining events. Running a bit behind but still targetting for the final release tag in June.

**Comment by kv2019i** [comment]
v2.10 tagged -> https://github.com/thesofproject/sof/tree/v2.10

**Comment by kv2019i** [comment]
https://www.sofproject.org/blog/2024/07/17/sof-2-10-0-is-here/
