### ISSUE TITLE
DELETED SOF 2.12 Release Checklist

### ISSUE THREAD

**Issue by kv2019i** [thesofproject/sof#9519]
Planned Timeline 
- to be decided in next SOF TSC (@lgirdwood to present)
- RC1 + Stable v2.12 Branch – TBD, 2025
- Final tag
- Target Release - TBD
- Overflow week (in case multiple RCs are required)

Pre-RC1 Steps, Creation of Stable Branch
- [ ] Tag features and issue list with milestone https://github.com/thesofproject/sof/milestones/v2.11
- [ ] Choose a SOF commit on main branch as candidate for stable branch
- [ ] Testing & sign off
- [ ] Branch stable v2.xx -- depending on main stability can be one week before RC1 or at the same time

RC1 Steps:
- [ ] Cherry pick critical features and bug fixes to stable-v2.xx for RC1
- [ ] Perform FW security scan and fix opens
- [ ] Testing & sign off
- [ ] Tag v2.xx-RC1

Final Release Steps:
- [ ] Cherry pick critical features and bug fixes to stable-v2.xx
- [ ] Testing & sign off
- [ ] Tag v2.xx release
- [ ] Publish release on https://github.com/thesofproject/sof/releases

Final Release, vendor specific steps / Intel:
- [ ] Production sign FW, upload FW and topology binaries to internal release folder
- [ ] Publish release on https://github.com/thesofproject/sof-bin/blob/main/HOWTO-new-release.md

Final Release, vendor specific steps / OtherVendor:
- add steps here

Final Steps:
- [ ] Declare the v2.xx release on https://www.sofproject.org/blog/
- [ ] Move any unfinished issues to next milestone

**Comment by kv2019i** [comment]
Replaced with https://github.com/thesofproject/sof/issues/9658
