### ISSUE TITLE
SOF 2.12 Release Checklist

### ISSUE THREAD

**Issue by kv2019i** [thesofproject/sof#9658]
Planned Timeline
- Stable v2.12 Branch and RC1 – w50 / 13th Dec
- RC2 – w2 / 10th Jan
- Target Release – w3 / 17th Jan
- Overflow week (in case more RCs are required) – w4

Pre-RC1 Steps, Creation of Stable Branch
- [x] Tag features and issue list with milestone https://github.com/thesofproject/sof/milestones/v2.12
- [x] Choose a SOF commit on main branch as candidate for stable branch https://github.com/thesofproject/sof/tree/v2.12-rc1
- [x] Tag branch point as rc1
- [x] Testing & sign off
- [x] Branch stable v2.xx -- depending on main stability can be one week before RC1 or at the same time https://github.com/thesofproject/sof/tree/stable-v2.12
- [x] Move any features in the milestone list that did not make it in time before the stable branch cut-off date, to the next release.
- [x] Update versions.json in mainline
- [x] Update versions.json in stable branch

RCx Steps:
- [x] Cherry pick critical features and bug fixes to stable-v2.xx for RCx
- [x] Perform FW security scan and fix opens
- [x] Testing & sign off
- [x] Tag v2.xx-RCx

Final Release Steps:
- [x] Cherry pick critical features and bug fixes to stable-v2.xx
- [x] Testing & sign off
- [x] Tag v2.xx release
- [x] Publish release on https://github.com/thesofproject/sof/releases

Final Release, vendor specific steps / Intel:
- [x] Production sign FW, upload FW and topology binaries to internal release folder
- [x] Publish release on https://github.com/thesofproject/sof-bin/blob/main/HOWTO-new-release.md

Final Release, vendor specific steps / OtherVendor:
- add steps here

Final Steps:
- [ ] Declare the v2.xx release on https://www.sofproject.org/blog/
- [x] Move any unfinished issues to next milestone

**Comment by kv2019i** [comment]
2.12-rc1 and stable-v2.12 branch created. I've modified the generic instructions to reflect the de facto practise of using "rc1" tag in the main branch as the branch point for the stable series. We've done this for a few releases and this seems to be a good practise. This makes it easy to see in main branch history, where the stable releases branched off.

FYI @thesofproject/maintainers

**Comment by kv2019i** [comment]
v2.12-rc2 tagged today https://github.com/thesofproject/sof/tree/v2.12-rc2

The milestone list is now empty and we have no P1 bugs filed, so based on current information, we have no expected changed and we can release final v2.12 next week.

**Comment by kv2019i** [comment]
v2.12 tagged! https://github.com/thesofproject/sof/tree/v2.12 

We'll next start preparing vendor binaries in sof-bin and make the release announcement when sof-bin binaries are ready!

**Comment by kv2019i** [comment]
Release notes drafted in github releases page for SOF, @thesofproject/steering-committee feel free to review. ETA for making the notes public, end of this week.

**Comment by kv2019i** [comment]
SOF2.12 and binary package 2025.01 are out! https://github.com/thesofproject/sof/releases/tag/v2.12 and https://github.com/thesofproject/sof-bin/releases

**Comment by kv2019i** [comment]
Closing this checklist with following notes:

- release announcement on https://www.sofproject.org/blog/ was not done . We are working on this to resume blob maintainance for 2.13.
- rest of items completed
- new checklist created for 2.13 https://github.com/thesofproject/sof/issues/9863
